### ISSUE TITLE
Fields of ascii format are written as hex by createVpd.py

### ISSUE THREAD

**Issue by AlexanderAmelkin** [open-power/vpdtools#18]
Could you please help debug and fix the problem we're having?
Attached please find the tarball with the VPD template file we're using.
Please pay attention to the VS keyword. It is of `ascii` type in the template.
However if I run `./createVpd.py -m mb-02051900A1.tvpd -o out`, and then run
`./reverseVpd.py -v out/mb-02051900A1.vpd`, I get the `mb-02051900A1.broken.tvpd` file where the VS keyword and many other to-be-ascii keywords of the original template file are listed as of `hex` type with `kwdata` containing the original string converted to hex.
What's wrong? Is it anything in my original template, or is it a flaw in `createVpd.py` ?

Attachment: [mb-02051900A1.tar.gz](https://github.com/open-power/vpdtools/files/3379415/mb-02051900A1.tar.gz)

**Comment by thejta** [comment]
reverseVpd.py is simply a convenience utility to create template files for VPD images that existed prior to the createVpd.py methodology.  The ascii/hex format is not specified in the actual vpd, so reverseVpd.py just does its best to guess at the input format.

It's not guaranteed that running reverseVpd.py will create a file equal to an input template for createVpd.py and shouldn't be used to cross check.  If createVpd.py runs without error, then your output vpd image should be fine.

**Comment by thejta** [comment]
Did my earlier response address the question?  Anything further to clarify or look into?  If not, I'll close this issue next week.

**Comment by AlexanderAmelkin** [comment]
Thank you for clarification. Good to know that my VPD is ok.

It's a pity though that reverseVpd doesn't respect the "Vital Product Data Records for POWER9 Scale Out Field Replaceable Units" spec that lists many keywords including `VS` as having an ASCII value.

**Comment by thejta** [comment]
The POWER9 VPD spec and the vpd file format are two independent, but related, things.  The vpd file format itself is processor agnostic, and unfortunately doesn't support specifying the data type in the file.  So the best thing the reverse script can do is take a best guess as to what the data was.
