### ISSUE TITLE
VPD Spec hidden behind login wall

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/vpdtools#6]
Not only that, but login appears broken for my at ibm.com mail address, so I cannot view the spec.

**Comment by youhour** [comment]
You can either use your IBM ID or your intranet ID.   I was not able to use my IBM ID though I already link it to intranet ID.  So, when you try to login choose the option with intranet ID.

**Comment by thejta** [comment]
I think the bigger question is why is the spec behind a login wall at all?  The tool to create images is public, why can't the document that describes that image be public as well?

**Comment by youhour** [comment]
That is some thing that I do not have control.  I was asked to work with the OpenPower publisher and they have put all short of document there.  This is to prevent unregister vendor from accessing it.

**Comment by stewart-ibm** [comment]
Maybe we should move the specification under the OpenPOWER Foundation?

That's certainly possible, and it'd mean that the spec could be both public and the source up on github.

**Comment by thejta** [comment]
I did some asking around and we can make it public where it's currently published.  I'm just awaiting one more sign off before we flip the switch.

**Comment by thejta** [comment]
The spec is now more open and the new URL is posted in the README.  It's on the IBM Portal for OpenPOWER.  It does require an account to download the file, but anyone can create an account.  This is the best solution for the issue, short of pulling the binary spec doc into this repo - which isn't ideal.

I'm going to close the issue, if not acceptable and have another solution - let me know.
